#!/usr/bin/env python3
"""
Interactive script to help set up your .env file with API keys.
Run this to quickly configure your backend.
"""
import os
import secrets
from pathlib import Path


def generate_secret_key():
    """Generate a secure random secret key."""
    return secrets.token_urlsafe(32)


def create_env_file():
    """Create .env file with user input."""
    print("=" * 60)
    print("Dependify 2.0 - Environment Setup")
    print("=" * 60)
    print("\nThis script will help you create a .env file with your API keys.")
    print("Press Enter to skip optional fields.\n")

    env_values = {}

    # Required fields
    print("📋 REQUIRED FIELDS:\n")

    env_values["GROQ_API_KEY"] = input("Groq API Key: ").strip()
    env_values["SUPABASE_URL"] = input("Supabase URL: ").strip()
    env_values["SUPABASE_KEY"] = input("Supabase Key (Service Role): ").strip()
    env_values["GITHUB_TOKEN"] = input("GitHub Personal Access Token: ").strip()

    # Generate secret key
    print("\n🔐 Generating API Secret Key...")
    env_values["API_SECRET_KEY"] = generate_secret_key()
    print(f"   Generated: {env_values['API_SECRET_KEY'][:20]}...")

    # Optional fields
    print("\n📋 OPTIONAL FIELDS (press Enter to skip):\n")

    github_client_id = input("GitHub OAuth Client ID [skip]: ").strip()
    if github_client_id:
        env_values["GITHUB_CLIENT_ID"] = github_client_id
        env_values["GITHUB_CLIENT_SECRET"] = input("GitHub OAuth Client Secret: ").strip()

    anthropic_key = input("Anthropic API Key (optional) [skip]: ").strip()
    if anthropic_key:
        env_values["ANTHROPIC_API_KEY"] = anthropic_key

    # Server configuration
    print("\n⚙️  SERVER CONFIGURATION:\n")

    port = input("Port [5000]: ").strip()
    env_values["PORT"] = port if port else "5000"

    frontend_url = input("Frontend URL [http://localhost:3000]: ").strip()
    env_values["FRONTEND_URL"] = frontend_url if frontend_url else "http://localhost:3000"

    rate_limit_min = input("Rate limit per minute [10]: ").strip()
    env_values["RATE_LIMIT_PER_MINUTE"] = rate_limit_min if rate_limit_min else "10"

    rate_limit_hour = input("Rate limit per hour [100]: ").strip()
    env_values["RATE_LIMIT_PER_HOUR"] = rate_limit_hour if rate_limit_hour else "100"

    # Write .env file
    print("\n📝 Writing .env file...")
    env_path = Path(__file__).parent / ".env"

    with open(env_path, "w") as f:
        f.write("# Dependify 2.0 Backend Configuration\n")
        f.write("# Generated by setup_env.py\n\n")

        f.write("# Groq API Configuration\n")
        f.write(f"GROQ_API_KEY={env_values.get('GROQ_API_KEY', '')}\n\n")

        f.write("# Supabase Configuration\n")
        f.write(f"SUPABASE_URL={env_values.get('SUPABASE_URL', '')}\n")
        f.write(f"SUPABASE_KEY={env_values.get('SUPABASE_KEY', '')}\n\n")

        f.write("# GitHub Configuration\n")
        f.write(f"GITHUB_TOKEN={env_values.get('GITHUB_TOKEN', '')}\n")
        if "GITHUB_CLIENT_ID" in env_values:
            f.write(f"GITHUB_CLIENT_ID={env_values['GITHUB_CLIENT_ID']}\n")
            f.write(f"GITHUB_CLIENT_SECRET={env_values['GITHUB_CLIENT_SECRET']}\n")
        f.write("\n")

        if "ANTHROPIC_API_KEY" in env_values:
            f.write("# Anthropic API (Optional)\n")
            f.write(f"ANTHROPIC_API_KEY={env_values['ANTHROPIC_API_KEY']}\n\n")

        f.write("# API Security\n")
        f.write(f"API_SECRET_KEY={env_values['API_SECRET_KEY']}\n\n")

        f.write("# Server Configuration\n")
        f.write(f"PORT={env_values['PORT']}\n")
        f.write(f"FRONTEND_URL={env_values['FRONTEND_URL']}\n\n")

        f.write("# Rate Limiting\n")
        f.write(f"RATE_LIMIT_PER_MINUTE={env_values['RATE_LIMIT_PER_MINUTE']}\n")
        f.write(f"RATE_LIMIT_PER_HOUR={env_values['RATE_LIMIT_PER_HOUR']}\n")

    print(f"✅ .env file created at: {env_path}")

    # Validate
    print("\n🔍 Validating configuration...")
    missing = []
    required = ["GROQ_API_KEY", "SUPABASE_URL", "SUPABASE_KEY", "GITHUB_TOKEN", "API_SECRET_KEY"]

    for key in required:
        if not env_values.get(key):
            missing.append(key)

    if missing:
        print(f"⚠️  WARNING: Missing required fields: {', '.join(missing)}")
        print("   Please edit .env file and add these values.")
    else:
        print("✅ All required fields are set!")

    # Next steps
    print("\n" + "=" * 60)
    print("🎉 Setup complete! Next steps:")
    print("=" * 60)
    print("\n1. Configure Modal secrets:")
    print("   modal token new")
    print(f"   modal secret create GROQ_API_KEY GROQ_API_KEY={env_values['GROQ_API_KEY'][:20]}...")
    print("   modal secret create SUPABASE_URL SUPABASE_URL=<your_url>")
    print("   modal secret create SUPABASE_KEY SUPABASE_KEY=<your_key>")
    print("\n2. Create Supabase table:")
    print("   Run the SQL from SETUP.md in your Supabase dashboard")
    print("\n3. Start the server:")
    print("   python server.py")
    print("\n4. Test the setup:")
    print("   python test_api.py")
    print("\n5. View API docs:")
    print("   http://localhost:5000/docs")
    print()


if __name__ == "__main__":
    # Check if .env already exists
    env_path = Path(__file__).parent / ".env"

    if env_path.exists():
        print("⚠️  .env file already exists!")
        response = input("Do you want to overwrite it? (yes/no): ").strip().lower()
        if response != "yes":
            print("Aborted. Existing .env file was not modified.")
            exit(0)
        print()

    try:
        create_env_file()
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled.")
        exit(1)
    except Exception as e:
        print(f"\n❌ Error: {e}")
        exit(1)
